import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/app/globals.css";
import { ReactNode } from "react";
import NavButtons from "@/components/NavButtons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="es" className={`${geistSans.variable} ${geistMono.variable} h-full`}>
      <body className="min-h-screen bg-background text-foreground antialiased">
        <div className="p-6">
          <NavButtons />
          {children}
          <footer className="mt-8 border-t pt-4 text-xs opacity-80">
            <p>Cuando yo hola yo chao asistentes contables.</p>
            <p>siii a todoo</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
